# Generated by Django 3.2 on 2021-05-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineshopuser',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
